import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';
import {dark} from "@clerk/themes";
import Provider from "@/app/Provider";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Live Docs",
  description: "Generated by live Docs.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider
      appearance={{
          baseTheme: dark,
          variables: {
              colorPrimary: '#3371ff',
              fontSize: '16px'
          }
      }}
      >
          <html lang="en">
          <body
              className={`${fontSans.variable} antialiased`}
          >
          <Provider>
              {children}
          </Provider>
          </body>
          </html>
      </ClerkProvider>
  );
}
